# Generated by Django 2.1.3 on 2019-01-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20190107_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Denied'), ('2', 'Approved'), ('3', 'Cancelled')], default='0', max_length=2),
        ),
    ]
