# Generated by Django 2.1.3 on 2019-01-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(default='United States', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='hirereason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='microphone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='scenario1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='scenario2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='scenario3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='screenshare',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='timededication',
            field=models.CharField(choices=[('1', '1-2 Hours'), ('2', '2-4 Hours'), ('3', '4-6 Hours'), ('4', '6-8 Hours'), ('5', 'More')], default='1', max_length=2),
        ),
    ]
